### ISSUE TITLE
Issues when using set or dict in parameters

### ISSUE THREAD

**Issue by jdolivet** [pamelafox/recursive-visualizations#16]
Hello,
first of all, thanks for your tool. I'm using it a lot and it's very usefull for my teaching.
I like the idea of seeing the parameters in each calls and it seems that it's not possible to see them when they are of type set or dict (it works with list, for example)
.In my case, I want to show the recursion calls in a DFS of a Graph.
I'm using a class Graphe building as a dict (with a method `__str__` or `__repr__` for printing him like a dict in the parameters) and a set to keep the nodes.
And neither of both is on the function calls.
I tried with a method `__repr__` to print always the same string and, even like this, the set is appearing just when it's an empty set (`set()`), when the set is not empty anymore, he's not appearing in the parameters anymore.
I suppose the numbers are like id of the functions and it's the default way when the `__repr__` or `__str__` is not usefull.
Maybe it's because both are using the `{` character...

Is there a way of fixing it?

Not sure if I was clear...
Sorry for my english

Thanks

Here is the [link of my example](https://www.recursionvisualizer.com/?function_definition=class%20Graphe%3A%0A%20%20%20%20%22%22%22Un%20graphe%20orient%C3%A9%20repr%C3%A9sent%C3%A9%20par%20un%20dictionnaire%20d'adjacence.%22%22%22%0A%0A%20%20%20%20def%20__init__%28self%29%3A%0A%20%20%20%20%20%20%20%20self.adj%20%3D%20dict%28%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20ajouter_sommet%28self%2C%20s%29%20-%3E%20None%3A%0A%20%20%20%20%20%20%20%20if%20s%20not%20in%20self.adj%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20self.adj%5Bs%5D%20%3D%20set%28%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20ajouter_arc%28self%2C%20s1%2C%20s2%29%20-%3E%20None%3A%0A%20%20%20%20%20%20%20%20self.ajouter_sommet%28s1%29%0A%20%20%20%20%20%20%20%20self.ajouter_sommet%28s2%29%0A%20%20%20%20%20%20%20%20self.adj%5Bs1%5D.add%28s2%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20arc%28self%2C%20s1%2C%20s2%29%20-%3E%20bool%3A%0A%20%20%20%20%20%20%20%20return%20s2%20in%20self.adj%5Bs1%5D%0A%20%20%20%20%0A%20%20%20%20def%20sommets%28self%29%20-%3E%20list%3A%0A%20%20%20%20%20%20%20%20return%20list%28self.adj%29%0A%20%20%20%20%0A%20%20%20%20def%20voisins%28self%2C%20s%29%20-%3E%20set%3A%0A%20%20%20%20%20%20%20%20return%20self.adj%5Bs%5D%0A%0A%20%20%20%20def%20__repr__%28self%29%3A%0A%20%20%20%20%20%20%20%20return%20str%28self.adj%29%0A%0Ag0%20%3D%20Graphe%28%29%0Ag0.ajouter_arc%28%22A%22%2C%20%22B%22%29%0Ag0.ajouter_arc%28%22A%22%2C%20%22D%22%29%0Ag0.ajouter_arc%28%22B%22%2C%20%22C%22%29%0Ag0.ajouter_arc%28%22C%22%2C%20%22E%22%29%0Ag0.ajouter_arc%28%22C%22%2C%20%22F%22%29%0Ag0.ajouter_arc%28%22D%22%2C%20%22E%22%29%0Ag0.ajouter_arc%28%22E%22%2C%20%22B%22%29%0Ag0.ajouter_arc%28%22G%22%2C%20%22C%22%29%0A%0Adef%20parcours%28g%2C%20vus%2C%20s%29%3A%0A%20%20%20%20%22%22%22Parcours%20en%20profondeur%20depuis%20le%20sommet%20s%22%22%22%0A%20%20%20%20if%20s%20not%20in%20vus%3A%0A%20%20%20%20%20%20%20%20vus.add%28s%29%0A%20%20%20%20%20%20%20%20for%20v%20in%20g.voisins%28s%29%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20parcours%28g%2C%20vus%2C%20v%29&function_call=parcours%28g0%2C%20set%28%29%2C%20%22A%22%29)

**Comment by pamelafox** [comment]
I'll check it out now, thanks for linking to the example.

**Comment by jdolivet** [comment]
Thanks a lot,
if it can help : 
here is the version with a static printing for the class (we can see that the set is being printed just when it's empty) : 
[static for class with set](https://www.recursionvisualizer.com/?function_definition=class%20Graphe%3A%0A%20%20%20%20%22%22%22Un%20graphe%20orient%C3%A9%20repr%C3%A9sent%C3%A9%20par%20un%20dictionnaire%20d'adjacence.%22%22%22%0A%0A%20%20%20%20def%20__init__%28self%29%3A%0A%20%20%20%20%20%20%20%20self.adj%20%3D%20dict%28%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20ajouter_sommet%28self%2C%20s%29%20-%3E%20None%3A%0A%20%20%20%20%20%20%20%20if%20s%20not%20in%20self.adj%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20self.adj%5Bs%5D%20%3D%20set%28%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20ajouter_arc%28self%2C%20s1%2C%20s2%29%20-%3E%20None%3A%0A%20%20%20%20%20%20%20%20self.ajouter_sommet%28s1%29%0A%20%20%20%20%20%20%20%20self.ajouter_sommet%28s2%29%0A%20%20%20%20%20%20%20%20self.adj%5Bs1%5D.add%28s2%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20arc%28self%2C%20s1%2C%20s2%29%20-%3E%20bool%3A%0A%20%20%20%20%20%20%20%20return%20s2%20in%20self.adj%5Bs1%5D%0A%20%20%20%20%0A%20%20%20%20def%20sommets%28self%29%20-%3E%20list%3A%0A%20%20%20%20%20%20%20%20return%20list%28self.adj%29%0A%20%20%20%20%0A%20%20%20%20def%20voisins%28self%2C%20s%29%20-%3E%20set%3A%0A%20%20%20%20%20%20%20%20return%20self.adj%5Bs%5D%0A%0A%20%20%20%20def%20__repr__%28self%29%3A%0A%20%20%20%20%20%20%20%20return%20%22graphe%22%0A%0Ag0%20%3D%20Graphe%28%29%0Ag0.ajouter_arc%28%22A%22%2C%20%22B%22%29%0Ag0.ajouter_arc%28%22A%22%2C%20%22D%22%29%0Ag0.ajouter_arc%28%22B%22%2C%20%22C%22%29%0Ag0.ajouter_arc%28%22C%22%2C%20%22E%22%29%0Ag0.ajouter_arc%28%22C%22%2C%20%22F%22%29%0Ag0.ajouter_arc%28%22D%22%2C%20%22E%22%29%0Ag0.ajouter_arc%28%22E%22%2C%20%22B%22%29%0Ag0.ajouter_arc%28%22G%22%2C%20%22C%22%29%0A%0Adef%20parcours%28g%2C%20vus%2C%20s%29%3A%0A%20%20%20%20%22%22%22Parcours%20en%20profondeur%20depuis%20le%20sommet%20s%22%22%22%0A%20%20%20%20if%20s%20not%20in%20vus%3A%0A%20%20%20%20%20%20%20%20vus.add%28s%29%0A%20%20%20%20%20%20%20%20for%20v%20in%20g.voisins%28s%29%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20parcours%28g%2C%20vus%2C%20v%29&function_call=parcours%28g0%2C%20set%28%29%2C%20%22A%22%29)

And same algo with list (working) : 
[static for class with list](https://www.recursionvisualizer.com/?function_definition=class%20Graphe%3A%0A%20%20%20%20%22%22%22Un%20graphe%20orient%C3%A9%20repr%C3%A9sent%C3%A9%20par%20un%20dictionnaire%20d'adjacence.%22%22%22%0A%0A%20%20%20%20def%20__init__%28self%29%3A%0A%20%20%20%20%20%20%20%20self.adj%20%3D%20dict%28%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20ajouter_sommet%28self%2C%20s%29%20-%3E%20None%3A%0A%20%20%20%20%20%20%20%20if%20s%20not%20in%20self.adj%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20self.adj%5Bs%5D%20%3D%20set%28%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20ajouter_arc%28self%2C%20s1%2C%20s2%29%20-%3E%20None%3A%0A%20%20%20%20%20%20%20%20self.ajouter_sommet%28s1%29%0A%20%20%20%20%20%20%20%20self.ajouter_sommet%28s2%29%0A%20%20%20%20%20%20%20%20self.adj%5Bs1%5D.add%28s2%29%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20def%20arc%28self%2C%20s1%2C%20s2%29%20-%3E%20bool%3A%0A%20%20%20%20%20%20%20%20return%20s2%20in%20self.adj%5Bs1%5D%0A%20%20%20%20%0A%20%20%20%20def%20sommets%28self%29%20-%3E%20list%3A%0A%20%20%20%20%20%20%20%20return%20list%28self.adj%29%0A%20%20%20%20%0A%20%20%20%20def%20voisins%28self%2C%20s%29%20-%3E%20set%3A%0A%20%20%20%20%20%20%20%20return%20self.adj%5Bs%5D%0A%0A%20%20%20%20def%20__repr__%28self%29%3A%0A%20%20%20%20%20%20%20%20return%20%22graphe%22%0A%0Ag0%20%3D%20Graphe%28%29%0Ag0.ajouter_arc%28%22A%22%2C%20%22B%22%29%0Ag0.ajouter_arc%28%22A%22%2C%20%22D%22%29%0Ag0.ajouter_arc%28%22B%22%2C%20%22C%22%29%0Ag0.ajouter_arc%28%22C%22%2C%20%22E%22%29%0Ag0.ajouter_arc%28%22C%22%2C%20%22F%22%29%0Ag0.ajouter_arc%28%22D%22%2C%20%22E%22%29%0Ag0.ajouter_arc%28%22E%22%2C%20%22B%22%29%0Ag0.ajouter_arc%28%22G%22%2C%20%22C%22%29%0A%0Adef%20parcours%28g%2C%20vus%2C%20s%29%3A%0A%20%20%20%20%22%22%22Parcours%20en%20profondeur%20depuis%20le%20sommet%20s%22%22%22%0A%20%20%20%20if%20s%20not%20in%20vus%3A%0A%20%20%20%20%20%20%20%20vus.append%28s%29%0A%20%20%20%20%20%20%20%20for%20v%20in%20g.voisins%28s%29%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20parcours%28g%2C%20vus%2C%20v%29&function_call=parcours%28g0%2C%20%5B%5D%2C%20%22A%22%29)

But the idea is to do it with set.

My thinking is that it can be linked with f-string because of the `{` for printing variable... 
But I don't have enough capacities to understand all the code...

**Comment by pamelafox** [comment]
I've merged my fix into main, should be live shortly. Please try it out and let me know how that works. You may need to clear your browser cache (I need to implement cache-busting, it appears).
