### ISSUE TITLE
Accept single-quote inputs

### ISSUE THREAD

**Issue by abdallahy271** [pamelafox/recursive-visualizations#3]
<img width="389" alt="Screen Shot 2022-03-08 at 5 29 17 PM" src="https://user-images.githubusercontent.com/56769914/157292667-48c40466-0e54-4aac-bf03-4406224721bb.png">

Currently, single-quoted strings return a Syntax Error when passed as argument to the function

**Comment by pamelafox** [comment]
Fixed thanks to #4
