### ISSUE TITLE
Lists are automatically ordered after passed as a parameter to the function

### ISSUE THREAD

**Issue by lrodri14** [pamelafox/recursive-visualizations#9]
Currently, when passing a list as a parameter, the list is automatically ordered after function acceptance, this makes it a little hard to keep the path of what the recursive function is returning or accepting, it would be nice if it keeps its order in each recursive call.

Example output: 
example = [4, 5, 1, 2, 3]

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/48039694/174129181-be239600-a606-4cdd-80a6-a3f78e55d9ac.png">

**Comment by pamelafox** [comment]
Thanks for report, replicated here:
https://www.recursionvisualizer.com/?function_definition=def%20partition%28l%2C%20r%2C%20nums%29%3A%0A%20%20%20%20%23%20Last%20element%20will%20be%20the%20pivot%20and%20the%20first%20element%20the%20pointer%0A%20%20%20%20pivot%2C%20ptr%20%3D%20nums%5Br%5D%2C%20l%0A%20%20%20%20for%20i%20in%20range%28l%2C%20r%29%3A%0A%20%20%20%20%20%20%20%20if%20nums%5Bi%5D%20%3C%3D%20pivot%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%23%20Swapping%20values%20smaller%20than%20the%20pivot%20to%20the%20front%0A%20%20%20%20%20%20%20%20%20%20%20%20nums%5Bi%5D%2C%20nums%5Bptr%5D%20%3D%20nums%5Bptr%5D%2C%20nums%5Bi%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20ptr%20%2B%3D%201%0A%20%20%20%20%23%20Finally%20swapping%20the%20last%20element%20with%20the%20pointer%20indexed%20number%0A%20%20%20%20nums%5Bptr%5D%2C%20nums%5Br%5D%20%3D%20nums%5Br%5D%2C%20nums%5Bptr%5D%0A%20%20%20%20return%20ptr%0A%20%0A%23%20With%20quicksort%28%29%20function%2C%20we%20will%20be%20utilizing%20the%20above%20code%20to%20obtain%20the%20pointer%0A%23%20at%20which%20the%20left%20values%20are%20all%20smaller%20than%20the%20number%20at%20pointer%20index%20and%20vice%20versa%0A%23%20for%20the%20right%20values.%0A%20%0A%20%0Adef%20quicksort%28l%2C%20r%2C%20nums%29%3A%0A%20%20%20%20if%20len%28nums%29%20%3D%3D%201%3A%20%20%23%20Terminating%20Condition%20for%20recursion.%20VERY%20IMPORTANT!%0A%20%20%20%20%20%20%20%20return%20nums%0A%20%20%20%20if%20l%20%3C%20r%3A%0A%20%20%20%20%20%20%20%20pi%20%3D%20partition%28l%2C%20r%2C%20nums%29%0A%20%20%20%20%20%20%20%20quicksort%28l%2C%20pi-1%2C%20nums%29%20%20%23%20Recursively%20sorting%20the%20left%20values%0A%20%20%20%20%20%20%20%20quicksort%28pi%2B1%2C%20r%2C%20nums%29%20%20%23%20Recursively%20sorting%20the%20right%20values%0A%20%20%20%20return%20nums&function_call=quicksort%280%2C%204%2C%20%5B4%2C%205%2C%201%2C%202%2C%203%5D%29

I'll look into it.

**Comment by pamelafox** [comment]
Should be fixed now!
